export const clientsDocumentMockData = [
  {
    id: 0,
    name: 'Договор аренды автомобиля №1023 (Иванов И.И.).pdf',
    size: '1.42 МБ',
    url: '/files/clients/contract-rent-1023-ivanov.pdf',
    date: '2025-12-18',
  },
  {
    id: 1,
    name: 'Акт приёма-передачи авто №1023 (Иванов И.И.).pdf',
    size: '684 КБ',
    url: '/files/clients/act-transfer-1023-ivanov.pdf',
    date: '2025-12-18',
  },
  {
    id: 2,
    name: 'Доп. соглашение №1 к договору №1023 (Иванов И.И.).pdf',
    size: '512 КБ',
    url: '/files/clients/add-agreement-1-1023-ivanov.pdf',
    date: '2026-01-05',
  },
  {
    id: 3,
    name: 'Скан паспорта (Иванов И.И.).jpg',
    size: '2.36 МБ',
    url: '/files/clients/passport-scan-ivanov.jpg',
    date: '2025-12-17',
  },
  {
    id: 4,
    name: 'Водительское удостоверение (Иванов И.И.).jpg',
    size: '1.18 МБ',
    url: '/files/clients/driver-license-ivanov.jpg',
    date: '2025-12-17',
  },
  {
    id: 5,
    name: 'Согласие на обработку персональных данных (Иванов И.И.).pdf',
    size: '248 КБ',
    url: '/files/clients/personal-data-consent-ivanov.pdf',
    date: '2025-12-17',
  },
  {
    id: 6,
    name: 'Счёт на оплату №551 (ООО «Альфа»).pdf',
    size: '326 КБ',
    url: '/files/clients/invoice-551-alfa.pdf',
    date: '2026-01-10',
  },
  {
    id: 7,
    name: 'Квитанция об оплате №551 (ООО «Альфа»).pdf',
    size: '194 КБ',
    url: '/files/clients/payment-receipt-551-alfa.pdf',
    date: '2026-01-10',
  },
  {
    id: 8,
    name: 'Договор корпоративного обслуживания №77 (ООО «Альфа»).pdf',
    size: '1.96 МБ',
    url: '/files/clients/corporate-contract-77-alfa.pdf',
    date: '2025-11-28',
  },
  {
    id: 9,
    name: 'Карточка клиента (ООО «Альфа»).xlsx',
    size: '97 КБ',
    url: '/files/clients/client-card-alfa.xlsx',
    date: '2025-11-28',
  },
  {
    id: 10,
    name: 'Претензия по повреждению ТС №18 (Петров П.П.).pdf',
    size: '842 КБ',
    url: '/files/clients/claim-damage-18-petrov.pdf',
    date: '2026-01-14',
  },
  {
    id: 11,
    name: 'Фото повреждений ТС (Петров П.П.).zip',
    size: '18.7 МБ',
    url: '/files/clients/damage-photos-petrov.zip',
    date: '2026-01-14',
  },
  {
    id: 12,
    name: 'Заявление на возврат залога (Сидорова А.А.).pdf',
    size: '271 КБ',
    url: '/files/clients/deposit-refund-request-sidorova.pdf',
    date: '2026-01-20',
  },
  {
    id: 13,
    name: 'Договор аренды автомобиля №1098 (Сидорова А.А.).pdf',
    size: '1.55 МБ',
    url: '/files/clients/contract-rent-1098-sidorova.pdf',
    date: '2026-01-19',
  },
  {
    id: 14,
    name: 'Акт сверки взаиморасчётов (ООО «Альфа») за 2025 год.pdf',
    size: '438 КБ',
    url: '/files/clients/reconciliation-act-alfa-2025.pdf',
    date: '2026-01-08',
  },
];
