export const transactions = [
  {
    id: 1,
    increse: true,
    sum: 28500,
    created_at: "2026-01-12",
    payer: "Иванов Артём Сергеевич",
    description: "Оплата аренды Toyota Camry",
    car_id: 0,
    car_name: "Toyota Camry",
  },
  {
    id: 2,
    increse: true,
    sum: 42000,
    created_at: "2026-01-08",
    payer: "Петрова Мария Викторовна",
    description: "Аренда авто на 3 дня оплачена",
    car_id: 0,
    car_name: "BMW 5 Series",
  },
  {
    id: 3,
    increse: true,
    sum: 17500,
    created_at: "2025-12-28",
    payer: "Сидоров Кирилл Андреевич",
    description: "Оплата аренды Kia Rio, сутки",
    car_id: 0,
    car_name: "Kia Rio",
  },
  {
    id: 4,
    increse: true,
    sum: 49900,
    created_at: "2025-12-19",
    payer: "Кузнецова Алина Романовна",
    description: "Оплата аренды Hyundai Tucson",
    car_id: 0,
    car_name: "Hyundai Tucson",
  },
  {
    id: 5,
    increse: true,
    sum: 31000,
    created_at: "2025-12-05",
    payer: "Смирнов Денис Олегович",
    description: "Продление аренды авто на 2 дня",
    car_id: 0,
    car_name: "Toyota Corolla",
  },
  {
    id: 6,
    increse: true,
    sum: 26000,
    created_at: "2025-11-26",
    payer: "Васильева Елена Игоревна",
    description: "Оплата аренды авто, тариф Комфорт",
    car_id: 0,
    car_name: "Honda Accord",
  },
  {
    id: 7,
    increse: true,
    sum: 38700,
    created_at: "2025-11-18",
    payer: "Николаев Максим Павлович",
    description: "Аренда авто на неделю, оплата",
    car_id: 0,
    car_name: "Audi A6",
  },
  {
    id: 8,
    increse: true,
    sum: 14900,
    created_at: "2025-11-09",
    payer: "Фёдоров Илья Никитич",
    description: "Оплата аренды авто Nissan Sunny",
    car_id: 0,
    car_name: "Nissan Sunny",
  },
  {
    id: 9,
    increse: true,
    sum: 45500,
    created_at: "2025-10-29",
    payer: "Орлова Дарья Александровна",
    description: "Оплата аренды авто Volkswagen Polo",
    car_id: 0,
    car_name: "Volkswagen Polo",
  },
  {
    id: 10,
    increse: false,
    sum: 21800,
    created_at: "2026-01-14",
    payer: "ООО АвтоСервис Центр",
    description: "Замена масла и фильтров Camry",
    car_id: 0,
    car_name: "Toyota Camry",
  },
  {
    id: 11,
    increse: false,
    sum: 13500,
    created_at: "2026-01-03",
    payer: "ИП Карпов Алексей Юрьевич",
    description: "Мойка, химчистка салона авто",
    car_id: 0,
    car_name: "Nissan Sunny",
  },
  {
    id: 12,
    increse: false,
    sum: 49200,
    created_at: "2025-12-22",
    payer: "ООО Шиномонтаж Профи",
    description: "Комплект шин и балансировка",
    car_id: 0,
    car_name: "Mercedes-Benz GLC",
  },
  {
    id: 13,
    increse: false,
    sum: 16800,
    created_at: "2025-12-10",
    payer: "Сервис АвтоПлюс",
    description: "Диагностика подвески и ремонт",
    car_id: 0,
    car_name: "Kia Rio",
  },
  {
    id: 14,
    increse: false,
    sum: 10400,
    created_at: "2025-11-30",
    payer: "АЗС ГазТрейд",
    description: "Топливо для автопарка, заправка",
    car_id: 0,
    car_name: "Toyota Corolla",
  },
  {
    id: 15,
    increse: false,
    sum: 22500,
    created_at: "2025-11-16",
    payer: "ООО Страхование Авто",
    description: "Страховой платёж по договору",
    car_id: 0,
    car_name: "Hyundai Tucson",
  },
  {
    id: 16,
    increse: false,
    sum: 15200,
    created_at: "2025-10-27",
    payer: "ИП Ремонт Кузова",
    description: "Покраска бампера после аренды",
    car_id: 0,
    car_name: "Volkswagen Polo",
  },
];

export const deposit = [
  {
    id: 1,
    increse: true,
    sum: 20000,
    created_at: "2026-01-11",
    payer: "Иванов Артём Сергеевич",
    description: "Депозит за аренду авто Camry",
    car_id: 0,
    car_name: "Toyota Camry",
  },
  {
    id: 2,
    increse: true,
    sum: 15000,
    created_at: "2026-01-05",
    payer: "Петрова Мария Викторовна",
    description: "Депозит за аренду Kia Rio",
    car_id: 0,
    car_name: "Kia Rio",
  },
  {
    id: 3,
    increse: true,
    sum: 30000,
    created_at: "2025-12-26",
    payer: "Сидоров Кирилл Андреевич",
    description: "Залог за аренду авто на 2 дня",
    car_id: 0,
    car_name: "Hyundai Tucson",
  },
  {
    id: 4,
    increse: true,
    sum: 25000,
    created_at: "2025-12-12",
    payer: "Кузнецова Алина Романовна",
    description: "Депозит за аренду Hyundai Tucson",
    car_id: 0,
    car_name: "Hyundai Tucson",
  },
  {
    id: 5,
    increse: true,
    sum: 18000,
    created_at: "2025-11-22",
    payer: "Николаев Максим Павлович",
    description: "Залог за аренду авто Volkswagen",
    car_id: 0,
    car_name: "Volkswagen Polo",
  },
  {
    id: 6,
    increse: true,
    sum: 22000,
    created_at: "2025-11-08",
    payer: "Орлова Дарья Александровна",
    description: "Депозит за аренду авто Polo",
    car_id: 0,
    car_name: "Volkswagen Polo",
  },
  {
    id: 7,
    increse: false,
    sum: 5000,
    created_at: "2026-01-15",
    payer: "Иванов Артём Сергеевич",
    description: "Частичный возврат залога клиенту",
    car_id: 0,
    car_name: "Toyota Camry",
  },
  {
    id: 8,
    increse: false,
    sum: 15000,
    created_at: "2026-01-09",
    payer: "Петрова Мария Викторовна",
    description: "Возврат депозита после аренды",
    car_id: 0,
    car_name: "Kia Rio",
  },
  {
    id: 9,
    increse: false,
    sum: 12000,
    created_at: "2025-12-30",
    payer: "Сидоров Кирилл Андреевич",
    description: "Возврат залога без повреждений",
    car_id: 0,
    car_name: "Toyota Corolla",
  },
  {
    id: 10,
    increse: false,
    sum: 7000,
    created_at: "2025-12-20",
    payer: "Кузнецова Алина Романовна",
    description: "Удержание за мойку, остаток вернули",
    car_id: 0,
    car_name: "Hyundai Tucson",
  },
  {
    id: 11,
    increse: false,
    sum: 18000,
    created_at: "2025-12-07",
    payer: "Смирнов Денис Олегович",
    description: "Возврат депозита по завершению",
    car_id: 0,
    car_name: "Toyota Corolla",
  },
  {
    id: 12,
    increse: false,
    sum: 9000,
    created_at: "2025-11-28",
    payer: "Васильева Елена Игоревна",
    description: "Удержание за штраф, часть залога",
    car_id: 0,
    car_name: "Nissan Sunny",
  },
  {
    id: 13,
    increse: false,
    sum: 14000,
    created_at: "2025-11-14",
    payer: "Николаев Максим Павлович",
    description: "Возврат залога клиенту после аренды",
    car_id: 0,
    car_name: "Volkswagen Polo",
  },
  {
    id: 14,
    increse: false,
    sum: 11000,
    created_at: "2025-10-31",
    payer: "Орлова Дарья Александровна",
    description: "Возврат депозита после проверки авто",
    car_id: 0,
    car_name: "Volkswagen Polo",
  },
];